<?php

namespace Fractalia\Bundle\SMSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SMSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SMSRepository extends EntityRepository
{
}
